### ISSUE TITLE
Tutorial 5: ant run issue

### ISSUE THREAD

**Issue by letuananh** [dakside/jhackshop#1]
@hoangducchinh: execute `ant run` right after cloned failed.

Please create a _new branch_ to fix this bug.

**Comment by hoangducchinh** [comment]
`dev` branch has been created

**Comment by letuananh** [comment]
@hoangducchinh: For your information: http://www.exubero.com/ant/dependencies.html

**Comment by hoangducchinh** [comment]
@letuananh : `ant run` failure is fixed with commit a521baf219f286a2298ca78fc2ce47c060545ed0
