### ISSUE TITLE
Tutorial 5: Compiling

### ISSUE THREAD

**Issue by letuananh** [dakside/jhackshop#2]
@hoangducchinh: Is there a way to auto build DakAlgo when one executes `ant run` in AlgoDemo? Right now DakAlgo needed to be compiled manually before compiling AlgoDemo.

**Comment by hoangducchinh** [comment]
@letuananh  Added auto build the external project DakAlgo when execute `ant run` or `ant build` in AlgoDemo with commit 8b955443900302156870143d2dd29ada8c34bd66 (the newer one is a521baf219f286a2298ca78fc2ce47c060545ed0)

**Comment by letuananh** [comment]
Tested & worked.
